name: new_site test
favicon: null
layout_spectrum: 0.8630993608385324
typography_spectrum: 0.478688849369064
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#3C493F'
    - '#7E8D85'
    - '#B3BFB8'
    - '#F0F7F4'
    - '#A2E3C4'
  brandStrength: 0.22372608724981546
  lightness: 0.248799110064283
  saturation: 0.28530069370754063
  rhythmicContrast: 0.2389440683182329
purpose: []
